name: Release and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release_and_deploy:
    runs-on: ubuntu-latest

    steps:
      ### 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      ### 2. Node.js 환경 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      ### 3. package.json에서 버전 읽기
      - name: Read Version from package.json
        id: read_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "Version from package.json: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      ### 4. 프로젝트 빌드 및 Docker 이미지 생성
      - name: Build Project and Create Docker Image
        env:
          CI: false
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
          REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}
          REACT_APP_GITHUB_CLIENT_ID: ${{ secrets.REACT_APP_GITHUB_CLIENT_ID }}
          REACT_APP_GITHUB_CLIENT_SECRET: ${{ secrets.REACT_APP_GITHUB_CLIENT_SECRET }}
        run: |
          # 필요한 패키지 설치
          npm install
          # 프로젝트 빌드
          npm run build
          # Docker 이미지 빌드
          docker build \
            --build-arg REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL \
            --build-arg REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL \
            --build-arg REACT_APP_FIREBASE_API_KEY=$REACT_APP_FIREBASE_API_KEY \
            --build-arg REACT_APP_FIREBASE_AUTH_DOMAIN=$REACT_APP_FIREBASE_AUTH_DOMAIN \
            --build-arg REACT_APP_FIREBASE_PROJECT_ID=$REACT_APP_FIREBASE_PROJECT_ID \
            --build-arg REACT_APP_FIREBASE_STORAGE_BUCKET=$REACT_APP_FIREBASE_STORAGE_BUCKET \
            --build-arg REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$REACT_APP_FIREBASE_MESSAGING_SENDER_ID \
            --build-arg REACT_APP_FIREBASE_APP_ID=$REACT_APP_FIREBASE_APP_ID \
            --build-arg REACT_APP_GITHUB_CLIENT_ID=$REACT_APP_GITHUB_CLIENT_ID \
            --build-arg REACT_APP_GITHUB_CLIENT_SECRET=$REACT_APP_GITHUB_CLIENT_SECRET \
            -t narrativa-admin .

      ### 5. Docker 이미지 저장(TAR 파일 생성)
      - name: Save Docker Image as TAR
        run: |
          docker save narrativa-admin -o narrativa-admin.tar

      ### 6. SSH 키 설정 및 디버깅
      - name: Setup SSH key
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/narraa-admin.pem
          chmod 600 ~/.ssh/narraa-admin.pem
          ls -l ~/.ssh/narraa-admin.pem
          file ~/.ssh/narraa-admin.pem

      ### 7. TAR 파일 업로드
      - name: Upload TAR to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          scp -i ~/.ssh/narraa-admin.pem -o StrictHostKeyChecking=no narrativa-admin.tar ubuntu@${{ secrets.EC2_HOST }}:~/

      ### 8. EC2에 접속하여 배포
      - name: Connect to EC2 and Deploy
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh -i ~/.ssh/narraa-admin.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            docker stop narrativa-admin || true
            docker rm narrativa-admin || true
            docker rmi narrativa-admin || true
            docker load -i narrativa-admin.tar
            docker run -d -p 3030:3030 --name narrativa-admin narrativa-admin
          EOF

      ### 9. Git PAT 설정
      - name: Configure Git to Use PAT
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}

      ### 10. 태그 생성 및 푸시
      - name: Create and Push Tag
        run: |
          TAG="v${{ env.VERSION }}"
          echo "Creating tag: $TAG"
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git tag $TAG
          git push origin $TAG

      ### 11. 릴리즈 노트 생성
      - name: Generate Release Notes
        id: generate_notes
        run: |
          echo "## Changes" > notes.md
          git log $(git describe --tags --abbrev=0)..HEAD --oneline >> notes.md
          echo "notes_body=$(cat notes.md)" >> $GITHUB_ENV

      ### 12. 릴리즈 생성
      - name: Create Release with Notes
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "Release v${{ env.VERSION }}"
          body: ${{ env.notes_body }}
          draft: false
          prerelease: false
